# Generated by Django 6.0.4 on 2026-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
