import type { FreelancerCardProps } from "./FreelancerCard";

export const PROFESSIONALS_API_URL = "http://localhost:8000/professionals/freelancers/";

export interface FreelancersResponse {
  freelancers: FreelancerCardProps[];
}

export const fallbackFreelancers: FreelancerCardProps[] = [
  {
    id: "seed-maria-garcia",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    name: "Maria Garcia",
    title: "UX/UI Designer",
    location: "Barcelona, Espana",
    rating: 5.0,
    reviews: 189,
    skills: ["Figma", "Adobe XD", "Branding", "Prototyping"],
    hourlyRate: 65,
    isVerified: true,
    bio: "Disena experiencias digitales limpias y modernas para productos SaaS, ecommerce y apps moviles. Le gusta trabajar de cerca con clientes para aterrizar ideas y convertirlas en flujos intuitivos.",
    experience: "6 anos en diseno de producto y experiencia de usuario",
    completedProjects: 124,
    responseTime: "Responde en 45 minutos",
    availability: "Disponible para empezar manana",
    category: "Diseno",
    featuredLabel: "Top Rated",
  },
  {
    id: "seed-ana-rodriguez",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    name: "Ana Rodriguez",
    title: "Digital Marketing Expert",
    location: "Valencia, Espana",
    rating: 4.8,
    reviews: 256,
    skills: ["SEO", "SEM", "Social Media", "Analytics"],
    hourlyRate: 55,
    isVerified: true,
    bio: "Especialista en estrategia de crecimiento, anuncios de rendimiento y posicionamiento organico. Suele trabajar con marcas que quieren escalar sus ventas y mejorar conversiones.",
    experience: "7 anos llevando trafico y conversion a marcas digitales",
    completedProjects: 181,
    responseTime: "Responde en 1 hora",
    availability: "Cupos abiertos esta semana",
    category: "Marketing",
    featuredLabel: "Mas contratado",
  },
  {
    id: "seed-david-lopez",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop",
    name: "David Lopez",
    title: "Video Editor & Motion Designer",
    location: "Sevilla, Espana",
    rating: 4.7,
    reviews: 98,
    skills: ["Premiere Pro", "After Effects", "DaVinci"],
    hourlyRate: 45,
    isVerified: false,
    bio: "Edita piezas dinamicas para redes, YouTube y anuncios. Su enfoque combina ritmo, narrativa y motion graphics con entregas rapidas y organizadas.",
    experience: "4 anos en edicion audiovisual y motion",
    completedProjects: 86,
    responseTime: "Responde en 2 horas",
    availability: "Disponible por proyecto",
    category: "Audiovisual",
  },
  {
    id: "seed-sofia-mendoza",
    avatar: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=200&h=200&fit=crop",
    name: "Sofia Mendoza",
    title: "Frontend Developer",
    location: "Bogota, Colombia",
    rating: 4.9,
    reviews: 142,
    skills: ["React", "TypeScript", "Tailwind", "Vite"],
    hourlyRate: 60,
    isVerified: true,
    bio: "Construye interfaces modernas y responsivas para startups y equipos de producto. Le importan mucho el detalle visual, la accesibilidad y el rendimiento.",
    experience: "5 anos desarrollando frontend para productos web",
    completedProjects: 109,
    responseTime: "Responde en 30 minutos",
    availability: "Disponible medio tiempo",
    category: "Desarrollo",
    featuredLabel: "Respuesta rapida",
  },
  {
    id: "seed-camilo-ruiz",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop",
    name: "Camilo Ruiz",
    title: "Backend Developer",
    location: "Medellin, Colombia",
    rating: 4.9,
    reviews: 117,
    skills: ["Django", "PostgreSQL", "APIs", "Docker"],
    hourlyRate: 62,
    isVerified: true,
    bio: "Desarrollador backend enfocado en APIs escalables, autenticacion y bases de datos. Suele ayudar a equipos a ordenar arquitectura y dejar procesos mantenibles.",
    experience: "6 anos construyendo sistemas y servicios backend",
    completedProjects: 97,
    responseTime: "Responde en 50 minutos",
    availability: "Disponible para proyectos largos",
    category: "Desarrollo",
  },
  {
    id: "seed-laura-paredes",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop",
    name: "Laura Paredes",
    title: "Brand Designer",
    location: "Quito, Ecuador",
    rating: 4.8,
    reviews: 88,
    skills: ["Branding", "Illustrator", "Packaging", "Social Kit"],
    hourlyRate: 48,
    isVerified: true,
    bio: "Desarrolla identidades visuales memorables para marcas personales y negocios emergentes. Le gusta mezclar estrategia, claridad y un sistema visual consistente.",
    experience: "5 anos en branding e identidad visual",
    completedProjects: 73,
    responseTime: "Responde en 1 hora",
    availability: "Disponible para nuevos clientes",
    category: "Diseno",
  },
  {
    id: "seed-julian-castro",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    name: "Julian Castro",
    title: "Data Analyst",
    location: "Lima, Peru",
    rating: 4.7,
    reviews: 69,
    skills: ["Python", "Power BI", "SQL", "Dashboards"],
    hourlyRate: 52,
    isVerified: false,
    bio: "Analiza datos de negocio y convierte informacion dispersa en dashboards y reportes accionables. Trabaja mucho con equipos comerciales, operativos y de producto.",
    experience: "4 anos en analitica y visualizacion de datos",
    completedProjects: 58,
    responseTime: "Responde en 3 horas",
    availability: "Disponible por entregables",
    category: "Datos",
  },
  {
    id: "seed-paula-vega",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&h=200&fit=crop",
    name: "Paula Vega",
    title: "Content Strategist",
    location: "Ciudad de Mexico, Mexico",
    rating: 4.9,
    reviews: 134,
    skills: ["Copywriting", "Content SEO", "Blogs", "Email"],
    hourlyRate: 46,
    isVerified: true,
    bio: "Crea estrategias de contenido y calendarios editoriales orientados a conversion. Su trabajo mezcla investigacion de audiencia, tono de marca y objetivos comerciales.",
    experience: "6 anos creando contenido para empresas digitales",
    completedProjects: 121,
    responseTime: "Responde en 1 hora",
    availability: "Disponible este mes",
    category: "Marketing",
    featuredLabel: "Mas contratado",
  },
  {
    id: "seed-esteban-mora",
    avatar: "https://images.unsplash.com/photo-1504593811423-6dd665756598?w=200&h=200&fit=crop",
    name: "Esteban Mora",
    title: "Mobile App Developer",
    location: "San Jose, Costa Rica",
    rating: 4.8,
    reviews: 91,
    skills: ["Flutter", "React Native", "Firebase", "Android"],
    hourlyRate: 58,
    isVerified: true,
    bio: "Desarrolla aplicaciones moviles para negocios y productos digitales. Trabaja en interfaces fluidas, integraciones y despliegues listos para tiendas.",
    experience: "5 anos creando apps moviles multiplataforma",
    completedProjects: 76,
    responseTime: "Responde en 1 hora",
    availability: "Disponible para MVPs y mejoras",
    category: "Desarrollo",
  },
  {
    id: "seed-valentina-rios",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&h=200&fit=crop",
    name: "Valentina Rios",
    title: "Customer Support Specialist",
    location: "Manizales, Colombia",
    rating: 4.9,
    reviews: 77,
    skills: ["CRM", "Chat Support", "Email Support", "Onboarding"],
    hourlyRate: 34,
    isVerified: true,
    bio: "Ayuda a empresas a estructurar procesos de atencion al cliente, soporte por chat y flujos de onboarding con un tono cercano y profesional.",
    experience: "4 anos optimizando experiencia de soporte",
    completedProjects: 63,
    responseTime: "Responde en 40 minutos",
    availability: "Disponible para soporte recurrente",
    category: "Soporte",
    featuredLabel: "Respuesta rapida",
  },
  {
    id: "seed-nicolas-suarez",
    avatar: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=200&h=200&fit=crop",
    name: "Nicolas Suarez",
    title: "Cybersecurity Consultant",
    location: "Buenos Aires, Argentina",
    rating: 4.8,
    reviews: 54,
    skills: ["Security Audit", "OWASP", "Pentesting", "DevSecOps"],
    hourlyRate: 72,
    isVerified: false,
    bio: "Realiza auditorias de seguridad, revisiones de vulnerabilidades y buenas practicas para equipos que quieren fortalecer sus productos web.",
    experience: "6 anos en seguridad ofensiva y consultoria",
    completedProjects: 49,
    responseTime: "Responde en 2 horas",
    availability: "Disponible por auditorias puntuales",
    category: "Seguridad",
  },
];

export const normalizeFreelancer = (freelancer: FreelancerCardProps): FreelancerCardProps => ({
  ...freelancer,
  bio:
    freelancer.bio ||
    `${freelancer.name} ofrece servicios como ${freelancer.title} y trabaja con enfoque en calidad, buena comunicacion y resultados claros para cada cliente.`,
  experience: freelancer.experience || "3+ anos de experiencia profesional",
  completedProjects: freelancer.completedProjects ?? Math.max(12, freelancer.reviews),
  responseTime: freelancer.responseTime || "Responde en menos de 2 horas",
  availability: freelancer.availability || "Disponible esta semana",
  category: freelancer.category || "General",
});

export const mergeFreelancers = (apiFreelancers: FreelancerCardProps[]) => {
  const normalizedApiFreelancers = apiFreelancers.map(normalizeFreelancer);
  if (normalizedApiFreelancers.length > 0) {
    return normalizedApiFreelancers;
  }

  return fallbackFreelancers;
};
